version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./projects/api/Dockerfile
    container_name: api-service
    env_file:
      - ./projects/api/.env
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - STORAGE_BACKEND=local
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - redis
    volumes:
      # Mount the API code for hot reload
      - ./projects/api:/app
      # Avoid overwriting node_modules with a volume
      - api_node_modules:/app/node_modules
      # Mount packages/db into the container for access
      - ./packages/db:/app/packages/db
      - uploads-data:/app/uploads
    command: npm run start:dev

  worker:
    build:
      context: .
      dockerfile: ./projects/worker/Dockerfile
    container_name: worker-service
    environment:
      - REDIS_URL=redis://redis:6379
      - STORAGE_BACKEND=local
    depends_on:
      - redis
    volumes:
      - ./projects/worker:/app
      - worker_node_modules:/app/node_modules
      - uploads-data:/app/uploads

  redis:
    image: redis:7
    container_name: redis

volumes:
  uploads-data:
  api_node_modules:
  worker_node_modules:
